### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by davidleejy** [ajylee/call_map#2]
Call Map appears to be an interesting project. However, it appears that the last commit was back in mid-2019. Does anyone know if this project is being actively maintained?

**Comment by ajylee** [comment]
No it has not being actively maintained. That said, the GPL / PyQt5 branch should work fine with current PyQt5 after my latest commit. There was only a minor change in the API.

The master / bsd-licensed / PySide2 branch needs more work, however.

**Comment by davidleejy** [comment]
Thanks for replying despite this project not being actively maintained. Wishing you the best in your future projects 🙂
